### ISSUE TITLE
Feature Request: getStatus();

### ISSUE THREAD

**Issue by Muddz** [Itiviti/simple-slack-api#196]
Hi! I really think we should have a `getStatus()` of users for when they forexample set their status for Vacation

**Comment by moults31** [comment]
Hey all, I implemented this straightforwardly in https://github.com/moults31/simple-slack-api/pull/6. @sandeep-yerramsetty or @Muddz, feel free to ping me to discuss improvements if you want! :)

**Comment by sandeep-yerramsetty** [comment]
I have made the changes required for this issue here:
 https://github.com/sandeep-yerramsetty/simple-slack-api/pull/3 
 
 @moults31  @Muddz
